apiVersion: v1
kind: Service
metadata:
  name: cityapp-service
spec:
  selector:
    app: cityapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
